import Head from "next/head"
import { BatteryPuzzle } from "../components/battery-puzzle"

export default function Home() {
    return (
        <div className="-translate-y-72 scale-[40%] sm:-translate-y-48 sm:scale-[60%] md:-translate-y-24 md:scale-75 lg:translate-y-0 lg:scale-100">
            <div className="flex h-full w-full flex-grow justify-center">
                <BatteryPuzzle />
                <Head>
                    <title>Create Next App!</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
            </div>
        </div>
    )
}
